name: "Terraform Github Action"
on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Github Action"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: AWS Sts Get Caller Identity
        run: aws sts get-caller-identity
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.2
      - name: Terraform fmt
        run: terraform fmt -recursive -check=true
      - name: Terraform Plan
        run: |
          terraform init
          terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve
